sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest SC_BACKEND=none
    - php: 7.0
      env: WP_VERSION=latest SC_BACKEND=none
    - php: 5.6
      env: WP_VERSION=latest SC_BACKEND=none
    - php: 5.6
      env: WP_VERSION=latest SC_BACKEND=redis
    - php: 5.6
      env: WP_VERSION=latest SC_BACKEND=memcached
    - php: 5.6
      env: WP_VERSION=trunk SC_BACKEND=none
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.5
      env: WP_VERSION=latest SC_BACKEND=none

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install --no-interaction --optimize-autoloader --prefer-dist

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      bash bin/install-object-cache.sh $SC_BACKEND
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs --ignore=vendor/ --standard=PSR2 $(find . -name '*.php')
    fi
